
(defvar expression)

(defun expression-to-lexemes-list(expression)
    (with-input-from-string (s expression)
        (let ((r nil))
            (do ((line (read s nil 'eof)
                       (read s nil 'eof)))
                ((eql line 'eof))
                (push line r)) 
            (reverse r)
        )
    )
)

(defun calc-reverse-polish-expression()
    (princ "Enter expression: ")
    (terpri)
    (setq expression (read-line))
    (terpri)
    (let ((stack nil))
        (loop for lexeme in (expression-to-lexemes-list expression) do 
            (cond 
                ((numberp lexeme)
                    (push lexeme stack)
                )
                ((symbolp lexeme)
                    (push (eval (cons lexeme (reverse (list (pop stack) (pop stack))))) stack)
                )
            )
        )
        (terpri)
        (princ "Result: ")
        (write (pop stack))
        (terpri)
    )
)

(calc-reverse-polish-expression)
